customhost = "//end-point of RDS database created//"
customuser = "//RDS database user-name//"
custompass = "//database password//"
customdb = "//MYSQL table name//"
custombucket = "//S3 bucket-name//"
customregion = "//region of RDS created//"
